[package]
name = "hola_soroban"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]   # necesario para generar .wasm

[dependencies]
soroban-sdk = "22.0.0"

[features]
default = ["testutils"]
testutils = ["soroban-sdk/testutils"]
